name: Increment Version

on:
  pull_request:
    branches: [ master ]

jobs:
  bump-version:
    name: Bump Version (master)
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Bump Patch Version
        uses: phips28/gh-action-bump-version@master
        with:
          version-type: patch
          skip-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
