name: Release Electron App

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 17.x
      - name: Install Dependencies
        run: npm install
      - name: Run Electron-Builder
        run: npm run electron:package:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
