name: Test Project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run weekly on Mondays at 8:22 UTC
  schedule: [ cron: '22 8 * * 1' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 17.x
      - name: Install Dependencies
        run: npm install
      - name: Test Application (with coverage)
        run: npm run test:coverage
      - name: Verify Taxon IDs
        run: npm run test:verify:taxa
